### ISSUE TITLE
How do I set the height and width?

### ISSUE THREAD

**Issue by matthewrice345** [jaredrummler/AnimatedSvgView#3]
It appears that regardless of the height/width in dp the Animated SVG is always much smaller. 

`<com.jrummyapps.android.widget.AnimatedSvgView
        android:id="@+id/animated_svg_view"
        android:layout_width="300dp"
        android:layout_height="300dp"
        android:layout_gravity="center"
        app:animatedSvgFillColors="@array/canvas_logo_colors"
        app:animatedSvgFillStart="1200"
        app:animatedSvgFillTime="1000"
        app:animatedSvgGlyphStrings="@array/canvas_logo_paths"
        app:animatedSvgImageSizeX="400"
        app:animatedSvgImageSizeY="400"
        app:animatedSvgTraceTime="2000"
        app:animatedSvgTraceTimePerGlyph="1000" />`

For example setting the view to 300dp it shows about 1/4 of the desired height/width. I also tried setting the viewportSize in code but that didn't help. 

`svgView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                svgView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                svgView.setViewportSize(svgView.getWidth(), svgView.getHeight());
            }
        });`

Any ideas on how to increase the AnimatedSvgView size?

**Comment by jaredrummler** [comment]
You need to set `app:animatedSvgImageSizeY` and `app:animatedSvgImageSizeX` to the width and height of the SVG. You can find this in the `viewBox` in the original SVG. This is the same as the `viewportWidth` or `viewportHeight` of a [VectorDrawable](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html).

**Comment by matthewrice345** [comment]
Thanks for the clarification, I think it's how I generated the paths for the SVG because if I scale it up from the original 200dp of my svg to 300dp and icrease the `animatedSvgImageSizeY` and `animatedSvgImageSizeX` to match it still doesn't scale. I'll regenerate and try again!

**Comment by jaredrummler** [comment]
This will also cause a problem:

``` java
svgView.setViewportSize(svgView.getWidth(), svgView.getHeight())
```

It will set the viewport size to the width and height of the actual view in pixels.
