### ISSUE TITLE
How to convert a png to the your format svg path array?

### ISSUE THREAD

**Issue by SwiftyWang** [jaredrummler/AnimatedSvgView#4]
I try some online png to svg tools, and get the path to the xml but it is not working. So how to use this lib use own image?

**Comment by ghost** [comment]
try GIMP, http://www.useragentman.com/blog/2013/04/26/how-to-create-svg-paths-easily-using-the-gimp/

**Comment by jaredrummler** [comment]
Sorry, I won't be providing help to convert a PNG to an SVG.
