### ISSUE TITLE
Can't get the 1.0.1 version from maven

### ISSUE THREAD

**Issue by farhadfaghihi** [jaredrummler/AnimatedSvgView#9]
The 1.0.1 version of the library has not been published on the maven repository. Please consider updating the artifacts, since we are going to use the new "mTraceMarkerLength" attribute. 
See the following link,  seems to be broken : 
https://repo1.maven.org/maven2/com/jaredrummler/animated-svg-view/1.0.1/animated-svg-view-1.0.1.aar

**Comment by jaredrummler** [comment]
I moved the artifact. The group id is now `com.jrummyapps`.

https://repo1.maven.org/maven2/com/jrummyapps/animated-svg-view/1.0.1/animated-svg-view-1.0.1.aar
